package io.github.greytaiwolf.botplayer.action.minecraft;

import io.github.greytaiwolf.botplayer.action.interaction.BlockCoordinates;
import io.github.greytaiwolf.botplayer.action.interaction.BlockTargetFingerprint;
import io.github.greytaiwolf.botplayer.kernel.BotServerPlayer;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.item.ItemEntity;
import net.neoforged.neoforge.event.level.BlockDropsEvent;

/**
 * Captures the exact vanilla item entity produced by one synchronous block-break packet.
 *
 * <p>The capture is armed only around {@code STOP_DESTROY_BLOCK}; it never retains a live
 * player, level, or item entity after that packet returns. {@link BlockDropsEvent} supplies
 * the still-unspawned entity UUID, item id, and count, which can subsequently be carried as
 * immutable action evidence. Any missing, duplicate, or non-exact event leaves no receipt.
 */
public final class BreakDropProvenanceCapture {
    private static final UUID ZERO_UUID = new UUID(0L, 0L);
    private static final ThreadLocal<ActiveCapture> ACTIVE = new ThreadLocal<>();

    private BreakDropProvenanceCapture() {
    }

    /**
     * Arms a same-thread capture around one already-validated STOP_DESTROY_BLOCK packet.
     */
    static Scope arm(
            BotServerPlayer player,
            BlockTargetFingerprint target,
            long generation) {
        Objects.requireNonNull(player, "player");
        Objects.requireNonNull(target, "target");
        if (generation <= 0L
                || player.runtimeHandle().generation() != generation
                || !target.dimension().value().equals(player.serverLevel()
                        .dimension().location().toString())) {
            throw new IllegalArgumentException(
                    "break-drop provenance arm does not match active bot");
        }
        if (ACTIVE.get() != null) {
            throw new IllegalStateException(
                    "nested block-drop provenance capture is not permitted");
        }
        ActiveCapture capture = new ActiveCapture(player, generation, target);
        ACTIVE.set(capture);
        return new Scope(capture);
    }

    /**
     * Receives the synchronous NeoForge drop event. Unrelated events are ignored; a second
     * event for the exact same captured source marks the receipt ambiguous.
     */
    public static void record(BlockDropsEvent event) {
        ActiveCapture capture = ACTIVE.get();
        if (capture != null) {
            capture.record(Objects.requireNonNull(event, "event"));
        }
    }

    /** Immutable proof that a particular ItemEntity was generated by the captured break. */
    public record Provenance(UUID entityId, String itemId, int count) {
        public Provenance {
            Objects.requireNonNull(entityId, "entityId");
            Objects.requireNonNull(itemId, "itemId");
            if (ZERO_UUID.equals(entityId) || count < 1 || count > 64) {
                throw new IllegalArgumentException(
                        "break-drop provenance is invalid");
            }
        }
    }

    /** Scope returned to the backend; it may expose a receipt only after being closed. */
    static final class Scope implements AutoCloseable {
        private final ActiveCapture capture;
        private boolean closed;

        private Scope(ActiveCapture capture) {
            this.capture = Objects.requireNonNull(capture, "capture");
        }

        @Override
        public void close() {
            if (!closed) {
                if (ACTIVE.get() != capture) {
                    throw new IllegalStateException(
                            "block-drop provenance capture ownership changed");
                }
                ACTIVE.remove();
                closed = true;
            }
        }

        Optional<Provenance> provenance() {
            if (!closed) {
                throw new IllegalStateException(
                        "block-drop provenance receipt read before close");
            }
            return capture.provenance();
        }
    }

    private static final class ActiveCapture {
        private final BotServerPlayer player;
        private final long generation;
        private final BlockTargetFingerprint target;
        private boolean matched;
        private boolean invalid;
        private Provenance provenance;

        private ActiveCapture(
                BotServerPlayer player,
                long generation,
                BlockTargetFingerprint target) {
            this.player = Objects.requireNonNull(player, "player");
            this.generation = generation;
            this.target = Objects.requireNonNull(target, "target");
        }

        private void record(BlockDropsEvent event) {
            if (!(event.getLevel() instanceof ServerLevel level)
                    || event.getBreaker() != player
                    || player.runtimeHandle().generation() != generation
                    || !target.dimension().value().equals(level.dimension()
                            .location().toString())
                    || !event.getPos().equals(position(target.position()))
                    || !MinecraftInteractionView.blockStateFingerprint(
                            event.getState()).equals(target.state())) {
                return;
            }
            if (matched) {
                invalid = true;
                return;
            }
            matched = true;
            if (event.getDrops().size() != 1) {
                invalid = true;
                return;
            }
            ItemEntity item = event.getDrops().getFirst();
            if (item == null || item.isRemoved() || item.getItem().isEmpty()
                    || ZERO_UUID.equals(item.getUUID())) {
                invalid = true;
                return;
            }
            int count = item.getItem().getCount();
            if (count < 1 || count > 64) {
                invalid = true;
                return;
            }
            provenance = new Provenance(item.getUUID(),
                    BuiltInRegistries.ITEM.getKey(item.getItem().getItem())
                            .toString(), count);
        }

        private Optional<Provenance> provenance() {
            return !matched || invalid || provenance == null
                    ? Optional.empty()
                    : Optional.of(provenance);
        }
    }

    private static BlockPos position(BlockCoordinates coordinates) {
        return new BlockPos(coordinates.x(), coordinates.y(), coordinates.z());
    }
}
