package io.github.greytaiwolf.botplayer.action;

public enum ActionKind {
   WAIT,
   LOOK_AT,
   MOVE_INPUT,
   CLIMB_INPUT,
   JUMP,
   SELECT_HOTBAR,
   SWAP_INVENTORY_HOTBAR,
   INVENTORY_MENU_SWAP,
   WORLD_MENU_TRANSACTION,
   WORLD_MENU_TRANSFER,
   WORLD_MENU_RECIPE,
   USE_ITEM,
   RELEASE_USE,
   USE_ON_BLOCK,
   PLACE_BLOCK,
   BREAK_BLOCK,
   ATTACK_ENTITY,
   INTERACT_ENTITY,
   DROP_SELECTED,
   PICKUP_WAIT,
   STOP;
}
