package io.github.greytaiwolf.botplayer.action;

public enum ActionFailureCode {
   NONE,
   INVALID_REQUEST,
   BOT_NOT_ACTIVE,
   STALE_GENERATION,
   DEADLINE_EXCEEDED,
   MAX_TICKS_EXCEEDED,
   DUPLICATE_IN_PROGRESS,
   IDEMPOTENCY_CONFLICT,
   LEDGER_CAPACITY_EXCEEDED,
   ACTION_ALIAS_CAPACITY_EXCEEDED,
   RUNTIME_CAPACITY_EXCEEDED,
   CHANNEL_BUSY,
   BACKEND_RESULT_MISMATCH,
   UNSAFE_CONTROL_STATE,
   PRECONDITION_FAILED,
   PERMISSION_DENIED,
   TARGET_UNAVAILABLE,
   UNSUPPORTED,
   CANCELLED,
   PREEMPTED,
   INTERNAL_ERROR;
}
