package io.github.greytaiwolf.botplayer.inventory;

public enum InventoryCloseReason {
   VIEWER_REQUEST,
   MENU_REPLACED,
   OPEN_FAILED,
   PERMISSION_REVOKED,
   OUT_OF_RANGE,
   DIMENSION_CHANGED,
   VIEWER_INVALID,
   BOT_NOT_ACTIVE,
   STALE_GENERATION,
   INVALID_BOT_INSTANCE,
   DANGER,
   BOT_DEATH,
   BOT_RESPAWN,
   BOT_DIMENSION_CHANGE,
   BOT_UNLOADED,
   VIEWER_DISCONNECTED,
   ITEM_CONSERVATION_FAILURE,
   SERVER_STOPPING;
}
