package io.github.greytaiwolf.botplayer.skill.checkpoint;

/** 恢复失败原因是固定代码，避免把未经限制的存档内容带入诊断。 */
public enum SkillCheckpointRecoveryRejection {
    CHECKPOINT_MISSING,
    CHECKPOINT_DAMAGED,
    CHECKPOINT_SCHEMA_UNSUPPORTED,
    SERVER_INSTANCE_MISMATCH,
    BOT_ID_MISMATCH,
    PLAYER_ID_MISMATCH,
    GENERATION_NOT_ADVANCED,
    CHECKPOINT_TERMINAL,
    CHECKPOINT_SCOPE_MISSING,
    PLAN_UNAVAILABLE,
    PLAN_VERSION_MISMATCH,
    DESCRIPTOR_UNAVAILABLE,
    MENU_STILL_OPEN,
    ACTION_NOT_QUIESCENT,
    CARRIED_STATE_NOT_EMPTY,
    OLD_GENERATION_TOKEN_PRESENT,
    REOBSERVATION_INCOMPLETE,
    SCOPE_FINGERPRINT_MISMATCH
}
