package io.github.greytaiwolf.botplayer.navigation;

public enum NavigationFailure {
    NONE,
    INVALID_REQUEST,
    BOT_NOT_ACTIVE,
    STALE_GENERATION,
    WRONG_DIMENSION,
    GOAL_OUT_OF_RANGE,
    SNAPSHOT_INCOMPLETE,
    UNLOADED_FRONTIER_TIMEOUT,
    NO_PATH,
    POLICY_BLOCKED,
    STUCK,
    ACTION_FAILED,
    DANGER_PREEMPTED,
    SUPPLY_REQUIRED,
    SERVER_OVERLOADED,
    BUDGET_EXHAUSTED,
    DEADLINE_EXCEEDED,
    CANCELLED,
    INTERNAL_ERROR
}
