package io.github.greytaiwolf.botplayer.skill.builtin.defense;

/** 给日志、技能运行时和测试使用的稳定、非本地化原因码。 */
public enum DefenseReason {
    READY,
    ACTION_IN_FLIGHT,
    ATTACK_ISSUED,
    RETREAT_LOW_HEALTH,
    RETREAT_OUT_OF_MELEE_RANGE,
    RETREAT_ATTACK_BUDGET_EXHAUSTED,
    ATTACK_COMPLETED,
    ATTACK_FAILED,
    RETREAT_COMPLETED,
    RETREAT_FAILED,
    TARGET_ELIMINATED,
    TARGET_CHANGED,
    PVP_TARGET_REJECTED,
    FRIENDLY_TARGET_REJECTED,
    TARGET_NOT_EXPLICIT_HOSTILE,
    RETREAT_BUDGET_EXHAUSTED,
    L0_SAFETY_PREEMPTED
}
