package io.github.greytaiwolf.botplayer.network.payload;

import io.github.greytaiwolf.botplayer.BotPlayer;
import io.github.greytaiwolf.botplayer.ai.AiMessage;
import io.github.greytaiwolf.botplayer.ai.AiMessageRole;
import io.github.greytaiwolf.botplayer.ai.AiRequestOptions;
import io.github.greytaiwolf.botplayer.ai.AiResponseFormat;
import io.github.greytaiwolf.botplayer.ai.transport.AiClientRequestDispatch;
import io.github.greytaiwolf.botplayer.ai.transport.AiRequestPurpose;
import java.nio.ByteBuffer;
import java.nio.charset.CharacterCodingException;
import java.nio.charset.CodingErrorAction;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.minecraft.resources.ResourceLocation;

/**
 * Server-to-owner-client envelope for one bounded, client-sponsored provider request.
 *
 * <p>All correlation identifiers are generated by the server-side proposal gate. This wire DTO
 * deliberately has no credential profile, key, Authorization value, provider endpoint, world
 * object, Firewall policy, or Skill runtime reference. The client must still verify its local
 * credential binding before it starts any Provider work, and the server treats the later
 * {@link AiProposalPayload} as untrusted.
 */
public record AiRequestDispatchPayload(AiClientRequestDispatch dispatch)
        implements CustomPacketPayload {
    public static final Type<AiRequestDispatchPayload> TYPE = new Type<>(
            ResourceLocation.fromNamespaceAndPath(BotPlayer.MOD_ID, "ai_request_dispatch"));

    public static final StreamCodec<RegistryFriendlyByteBuf, AiRequestDispatchPayload>
            STREAM_CODEC = StreamCodec.of(
                    AiRequestDispatchPayload::encode,
                    AiRequestDispatchPayload::decode);

    public AiRequestDispatchPayload {
        dispatch = Objects.requireNonNull(dispatch, "dispatch");
    }

    private static void encode(
            RegistryFriendlyByteBuf buffer, AiRequestDispatchPayload payload) {
        AiClientRequestDispatch dispatch = payload.dispatch;
        buffer.writeUUID(dispatch.serverInstanceId());
        buffer.writeUUID(dispatch.botId());
        buffer.writeUUID(dispatch.ownerId());
        buffer.writeUUID(dispatch.agentId());
        buffer.writeLong(dispatch.generation());
        buffer.writeUUID(dispatch.requestId());
        buffer.writeUUID(dispatch.nonce());
        buffer.writeLong(dispatch.revision());
        buffer.writeEnum(dispatch.purpose());
        buffer.writeLong(dispatch.issuedAtTick());
        buffer.writeLong(dispatch.expiresAtTick());
        buffer.writeLong(dispatch.issuedAtEpochMillis());
        buffer.writeLong(dispatch.expiresAtEpochMillis());
        writeUtf(buffer, dispatch.providerId(), 64);
        writeUtf(buffer, dispatch.model(), 128);
        buffer.writeVarInt(dispatch.messages().size());
        for (AiMessage message : dispatch.messages()) {
            buffer.writeEnum(message.role());
            writeUtf(buffer, message.content(),
                    AiClientRequestDispatch.MAX_MESSAGE_UTF8_BYTES);
        }
        AiRequestOptions options = dispatch.options();
        buffer.writeVarInt(options.maximumOutputTokens());
        buffer.writeLong(options.timeoutMillis());
        buffer.writeEnum(options.responseFormat());
        buffer.writeBoolean(options.reasoningAllowed());
        buffer.writeBoolean(options.toolCallsAllowed());
        buffer.writeBoolean(options.temperature().isPresent());
        options.temperature().ifPresent(buffer::writeDouble);
        buffer.writeBoolean(dispatch.responseSchemaJson().isPresent());
        dispatch.responseSchemaJson().ifPresent(value -> writeUtf(
                buffer, value, AiClientRequestDispatch.MAX_RESPONSE_SCHEMA_UTF8_BYTES));
    }

    private static AiRequestDispatchPayload decode(RegistryFriendlyByteBuf buffer) {
        UUID serverInstanceId = buffer.readUUID();
        UUID botId = buffer.readUUID();
        UUID ownerId = buffer.readUUID();
        UUID agentId = buffer.readUUID();
        long generation = buffer.readLong();
        UUID requestId = buffer.readUUID();
        UUID nonce = buffer.readUUID();
        long revision = buffer.readLong();
        AiRequestPurpose purpose = buffer.readEnum(AiRequestPurpose.class);
        long issuedAtTick = buffer.readLong();
        long expiresAtTick = buffer.readLong();
        long issuedAtEpochMillis = buffer.readLong();
        long expiresAtEpochMillis = buffer.readLong();
        String providerId = readUtf(buffer, 64, "providerId").value;
        String model = readUtf(buffer, 128, "model").value;
        int messageCount = buffer.readVarInt();
        if (messageCount < 1 || messageCount > AiClientRequestDispatch.MAX_MESSAGES) {
            throw new IllegalArgumentException("message count is outside the allowed range");
        }
        List<AiMessage> messages = new ArrayList<>(messageCount);
        int messageBytes = 0;
        for (int index = 0; index < messageCount; index++) {
            AiMessageRole role = buffer.readEnum(AiMessageRole.class);
            DecodedUtf8 content = readUtf(
                    buffer,
                    Math.min(
                            AiClientRequestDispatch.MAX_MESSAGE_UTF8_BYTES,
                            AiClientRequestDispatch.MAX_TOTAL_MESSAGE_UTF8_BYTES
                                    - messageBytes),
                    "message content");
            messageBytes = addWithinTotal(
                    messageBytes,
                    content.byteLength,
                    AiClientRequestDispatch.MAX_TOTAL_MESSAGE_UTF8_BYTES,
                    "message content");
            messages.add(new AiMessage(role, content.value));
        }
        int maximumOutputTokens = buffer.readVarInt();
        long timeoutMillis = buffer.readLong();
        AiResponseFormat responseFormat = buffer.readEnum(AiResponseFormat.class);
        boolean reasoningAllowed = buffer.readBoolean();
        boolean toolCallsAllowed = buffer.readBoolean();
        Optional<Double> temperature = buffer.readBoolean()
                ? Optional.of(buffer.readDouble())
                : Optional.empty();
        Optional<String> responseSchemaJson = buffer.readBoolean()
                ? Optional.of(readUtf(
                        buffer,
                        AiClientRequestDispatch.MAX_RESPONSE_SCHEMA_UTF8_BYTES,
                        "responseSchemaJson").value)
                : Optional.empty();

        return new AiRequestDispatchPayload(new AiClientRequestDispatch(
                serverInstanceId,
                botId,
                ownerId,
                agentId,
                generation,
                requestId,
                nonce,
                revision,
                purpose,
                issuedAtTick,
                expiresAtTick,
                issuedAtEpochMillis,
                expiresAtEpochMillis,
                providerId,
                model,
                messages,
                new AiRequestOptions(
                        maximumOutputTokens,
                        timeoutMillis,
                        responseFormat,
                        reasoningAllowed,
                        toolCallsAllowed,
                        temperature),
                responseSchemaJson));
    }

    private static void writeUtf(
            RegistryFriendlyByteBuf buffer, String value, int maximumUtf8Bytes) {
        byte[] encoded = value.getBytes(StandardCharsets.UTF_8);
        if (encoded.length > maximumUtf8Bytes) {
            throw new IllegalArgumentException(
                    "string exceeds maximum UTF-8 bytes " + maximumUtf8Bytes);
        }
        buffer.writeVarInt(encoded.length);
        buffer.writeBytes(encoded);
    }

    private static DecodedUtf8 readUtf(
            RegistryFriendlyByteBuf buffer, int maximumUtf8Bytes, String name) {
        if (maximumUtf8Bytes < 0) {
            throw new IllegalArgumentException(
                    name + " has no remaining UTF-8 byte budget");
        }
        int byteLength = buffer.readVarInt();
        if (byteLength < 0 || byteLength > maximumUtf8Bytes) {
            throw new IllegalArgumentException(
                    name + " exceeds maximum UTF-8 bytes " + maximumUtf8Bytes);
        }
        if (byteLength > buffer.readableBytes()) {
            throw new IllegalArgumentException(
                    name + " byte length exceeds remaining payload");
        }
        byte[] encoded = new byte[byteLength];
        buffer.readBytes(encoded);
        try {
            String value = StandardCharsets.UTF_8.newDecoder()
                    .onMalformedInput(CodingErrorAction.REPORT)
                    .onUnmappableCharacter(CodingErrorAction.REPORT)
                    .decode(ByteBuffer.wrap(encoded))
                    .toString();
            return new DecodedUtf8(value, byteLength);
        } catch (CharacterCodingException exception) {
            throw new IllegalArgumentException(name + " is not valid UTF-8", exception);
        }
    }

    private static int addWithinTotal(
            int current, int additional, int maximum, String name) {
        if (additional > maximum - current) {
            throw new IllegalArgumentException(
                    name + " exceeds maximum UTF-8 bytes " + maximum);
        }
        return current + additional;
    }

    @Override
    public Type<AiRequestDispatchPayload> type() {
        return TYPE;
    }

    /** Delegate diagnostic intentionally omits nonce and all prompt/schema content. */
    @Override
    public String toString() {
        return "AiRequestDispatchPayload[" + dispatch + "]";
    }

    private static final class DecodedUtf8 {
        private final String value;
        private final int byteLength;

        private DecodedUtf8(String value, int byteLength) {
            this.value = Objects.requireNonNull(value, "value");
            this.byteLength = byteLength;
        }
    }
}
